import {
  Therapist, Room, PlanType, Patient, PatientPlan,
  Appointment, ClinicalNote, WhatsAppConfig,
  InventoryItem, InventoryPurchase, Payment
} from './types';

export const therapists: Therapist[] = [
  { id: 't1', name: 'Ana López',        email: 'ana@consultorio.pe',   color: '#3B82F6', bgColor: 'bg-blue-500',    isActive: true, startHour: 9,  endHour: 18, lunchStart: 13, lunchEnd: 14, workingDays: [1,2,3,4,5] },
  { id: 't2', name: 'Pedro García',     email: 'pedro@consultorio.pe', color: '#10B981', bgColor: 'bg-emerald-500', isActive: true, startHour: 10, endHour: 18, lunchStart: 13, lunchEnd: 14, workingDays: [1,2,3,4,5] },
  { id: 't3', name: 'Laura Martínez',   email: 'laura@consultorio.pe', color: '#F59E0B', bgColor: 'bg-amber-500',   isActive: true, startHour: 9,  endHour: 17, lunchStart: 13, lunchEnd: 14, workingDays: [1,2,3,4,5] },
];

export const rooms: Room[] = [
  { id: 'r1', name: 'Habitación 1', isActive: true },
  { id: 'r2', name: 'Habitación 2', isActive: true },
  { id: 'r3', name: 'Habitación 3', isActive: true },
];

export const planTypes: PlanType[] = [
  { id: 'p1', name: 'Pack 6 sesiones',  sessionCount: 6,  price: 650,  description: 'S/. 108 por sesión' },
  { id: 'p2', name: 'Pack 10 sesiones', sessionCount: 10, price: 1050, description: 'S/. 105 por sesión' },
  { id: 'p3', name: 'Pack 15 sesiones', sessionCount: 15, price: 1550, description: 'S/. 103 por sesión' },
];

export const patients: Patient[] = [
  {
    id: 'pa1', name: 'María González', dni: '47234589', birthDate: '1989-05-22',
    address: 'Av. Salaverry 1820, Jesús María', occupation: 'Contadora',
    weight: 62, height: 165, phone: '+51987234567', email: 'maria.gonzalez@gmail.com',
    consultationReason: 'Dolor lumbar crónico por postura en oficina',
    previousTreatments: true, previousTreatmentsDetail: 'Sesiones de fisioterapia hace 1 año',
    exams: 'Resonancia magnética lumbar (2025): protrusión L4-L5',
    allergies: 'Ninguna conocida', isPregnant: false,
    referralSource: 'Recomendación de su hermana',
    assignedTherapistId: 't1', createdAt: '2025-08-10',
    emergencyContactName: 'Carlos González', emergencyContactPhone: '+51987111222', emergencyContactRelationship: 'Esposo/a',
    chronicConditions: ['Hipertensión arterial'], currentMedications: 'Losartán 50mg diario',
    initialPainLevel: 7, workPosture: 'sedentary', physicalActivity: 'occasional',
    painZone: 'Lumbar', dominantHand: 'right',
  },
  {
    id: 'pa2', name: 'Carlos Rodríguez', dni: '43567812', birthDate: '1985-11-08',
    address: 'Calle Berlín 450, Miraflores', occupation: 'Ingeniero de sistemas',
    weight: 78, height: 175, phone: '+51976543210', email: 'carlos.rodriguez@gmail.com',
    consultationReason: 'Cervicalgia y tensión muscular en hombros',
    previousTreatments: false, previousTreatmentsDetail: '',
    exams: 'Sin estudios previos',
    allergies: 'Penicilina', isPregnant: false,
    referralSource: 'Búsqueda en Google',
    assignedTherapistId: 't2', createdAt: '2025-10-05',
    emergencyContactName: 'Pedro Rodríguez', emergencyContactPhone: '+51976111000', emergencyContactRelationship: 'Padre',
    chronicConditions: [], currentMedications: '',
    initialPainLevel: 6, workPosture: 'sedentary', physicalActivity: 'regular',
    painZone: 'Cervical', dominantHand: 'right',
  },
  {
    id: 'pa3', name: 'Sofía Fernández', dni: '72456789', birthDate: '1995-05-15',
    address: 'Jr. Junín 234, San Isidro', occupation: 'Diseñadora gráfica',
    weight: 55, height: 160, phone: '+51954321098', email: 'sofia.fernandez@gmail.com',
    consultationReason: 'Dolor de espalda alta por uso de laptop',
    previousTreatments: false, previousTreatmentsDetail: '',
    exams: '', allergies: '', isPregnant: false,
    referralSource: 'Instagram del consultorio',
    assignedTherapistId: 't3', createdAt: '2025-11-20',
    emergencyContactName: 'María Fernández', emergencyContactPhone: '+51954000111', emergencyContactRelationship: 'Madre',
    chronicConditions: [], currentMedications: '',
    initialPainLevel: 5, workPosture: 'sedentary', physicalActivity: 'occasional',
    painZone: 'Dorsal', dominantHand: 'right',
  },
  {
    id: 'pa4', name: 'Diego Morales', dni: '61234567', birthDate: '1992-07-30',
    address: 'Av. Brasil 2580, Pueblo Libre', occupation: 'Vendedor',
    weight: 82, height: 178, phone: '+51932109876', email: 'diego.morales@gmail.com',
    consultationReason: 'Lesión deportiva en rodilla derecha',
    previousTreatments: true, previousTreatmentsDetail: 'Tratamiento con kinesiólogo (3 meses)',
    exams: 'Ecografía rodilla: tendinitis rotuliana',
    allergies: 'Antiinflamatorios (ibuprofeno)', isPregnant: false,
    referralSource: 'Recomendación del Dr. Arenas',
    assignedTherapistId: 't1', createdAt: '2025-09-03',
    emergencyContactName: 'Laura Morales', emergencyContactPhone: '+51932000222', emergencyContactRelationship: 'Esposo/a',
    chronicConditions: [], currentMedications: 'Paracetamol según necesidad',
    initialPainLevel: 8, workPosture: 'mixed', physicalActivity: 'regular',
    painZone: 'Rodilla', dominantHand: 'right',
  },
  {
    id: 'pa5', name: 'Valentina Torres', dni: '76543210', birthDate: '1998-05-14',
    address: 'Calle Las Camelias 380, San Borja', occupation: 'Estudiante de psicología',
    weight: 58, height: 168, phone: '+51910987654', email: 'vale.torres@gmail.com',
    consultationReason: 'Postura encorvada y dolor escapular',
    previousTreatments: false, previousTreatmentsDetail: '',
    exams: '', allergies: 'Polen', isPregnant: false,
    referralSource: 'Su mamá es paciente',
    assignedTherapistId: 't2', createdAt: '2025-07-15',
    emergencyContactName: 'Rosa Torres', emergencyContactPhone: '+51910000333', emergencyContactRelationship: 'Madre',
    chronicConditions: [], currentMedications: '',
    initialPainLevel: 4, workPosture: 'sedentary', physicalActivity: 'occasional',
    painZone: 'Dorsal', dominantHand: 'right',
  },
  {
    id: 'pa6', name: 'Martín Herrera', dni: '42109876', birthDate: '1980-09-25',
    address: 'Av. Aviación 4920, Surquillo', occupation: 'Ejecutivo de ventas',
    weight: 90, height: 180, phone: '+51988765432', email: 'martin.herrera@gmail.com',
    consultationReason: 'Lumbalgia recurrente y dolor ciático',
    previousTreatments: true, previousTreatmentsDetail: 'Múltiples sesiones con quiropráctico',
    exams: 'RMN lumbar (2024): hernia L5-S1',
    allergies: 'Ninguna', isPregnant: false,
    referralSource: 'Recomendación personal',
    assignedTherapistId: 't3', createdAt: '2026-01-08',
    emergencyContactName: 'Patricia Herrera', emergencyContactPhone: '+51988000444', emergencyContactRelationship: 'Esposo/a',
    chronicConditions: ['Diabetes', 'Hipertensión arterial'], currentMedications: 'Metformina 850mg c/12h, Enalapril 10mg',
    initialPainLevel: 9, workPosture: 'sedentary', physicalActivity: 'none',
    painZone: 'Lumbar', dominantHand: 'right',
  },
  {
    id: 'pa7', name: 'Camila Ruiz', dni: '58901234', birthDate: '1993-05-28',
    address: 'Jr. Las Flores 1240, Magdalena', occupation: 'Enfermera',
    weight: 64, height: 162, phone: '+51966543210', email: 'camila.ruiz@gmail.com',
    consultationReason: 'Tensión cervical y migrañas tensionales',
    previousTreatments: true, previousTreatmentsDetail: 'Acupuntura hace 6 meses (efectiva)',
    exams: 'Sin estudios recientes',
    allergies: 'Látex', isPregnant: false,
    referralSource: 'Compañera del hospital',
    assignedTherapistId: 't1', createdAt: '2025-06-20',
    emergencyContactName: 'Roberto Ruiz', emergencyContactPhone: '+51966000555', emergencyContactRelationship: 'Esposo/a',
    chronicConditions: [], currentMedications: '',
    initialPainLevel: 7, workPosture: 'active', physicalActivity: 'occasional',
    painZone: 'Cervical', dominantHand: 'right',
  },
  {
    id: 'pa8', name: 'Felipe Castro', dni: '39012345', birthDate: '1987-04-18',
    address: 'Calle Tarata 280, Miraflores', occupation: 'Chef',
    weight: 75, height: 173, phone: '+51944321098', email: 'felipe.castro@gmail.com',
    consultationReason: 'Dolor en muñecas por trabajo manual repetitivo',
    previousTreatments: false, previousTreatmentsDetail: '',
    exams: '', allergies: '', isPregnant: false,
    referralSource: 'Facebook',
    assignedTherapistId: 't2', createdAt: '2026-02-14',
    emergencyContactName: 'Ana Castro', emergencyContactPhone: '+51944000666', emergencyContactRelationship: 'Madre',
    chronicConditions: [], currentMedications: '',
    initialPainLevel: 6, workPosture: 'active', physicalActivity: 'occasional',
    painZone: 'Muñeca / Mano', dominantHand: 'right',
  },
  {
    id: 'pa9', name: 'Isadora Vargas', dni: '65432109', birthDate: '1991-08-07',
    address: 'Av. Javier Prado 3650, San Borja', occupation: 'Abogada',
    weight: 65, height: 170, phone: '+51922109876', email: 'isadora.vargas@gmail.com',
    consultationReason: 'Embarazo, dolor lumbar y cervical en 5to mes',
    previousTreatments: false, previousTreatmentsDetail: '',
    exams: 'Ecografía obstétrica al día', allergies: 'Ninguna',
    isPregnant: true,
    referralSource: 'Obstetra (Dra. Salinas)',
    assignedTherapistId: 't3', createdAt: '2025-12-01',
    emergencyContactName: 'Javier Vargas', emergencyContactPhone: '+51922000777', emergencyContactRelationship: 'Esposo/a',
    chronicConditions: [], currentMedications: 'Ácido fólico, vitaminas prenatales',
    initialPainLevel: 6, workPosture: 'sedentary', physicalActivity: 'occasional',
    painZone: 'Lumbar', dominantHand: 'right',
  },
  {
    id: 'pa10', name: 'Benjamín Silva', dni: '71098765', birthDate: '1996-05-11',
    address: 'Calle Mártir Olaya 162, Miraflores', occupation: 'Desarrollador web',
    weight: 70, height: 176, phone: '+51900987654', email: 'benjamin.silva@gmail.com',
    consultationReason: 'Túnel carpiano leve y dolor cervical',
    previousTreatments: false, previousTreatmentsDetail: '',
    exams: 'EMG: compresión leve nervio mediano derecho',
    allergies: '', isPregnant: false,
    referralSource: 'Búsqueda en Google',
    assignedTherapistId: 't1', createdAt: '2026-03-05',
    emergencyContactName: 'Sofía Silva', emergencyContactPhone: '+51900000888', emergencyContactRelationship: 'Hermano/a',
    chronicConditions: [], currentMedications: '',
    initialPainLevel: 5, workPosture: 'sedentary', physicalActivity: 'regular',
    painZone: 'Cervical', dominantHand: 'right',
  },
];

export const patientPlans: PatientPlan[] = [
  { id: 'pp1', patientId: 'pa1', planTypeId: 'p2', totalSessions: 10, usedSessions: 6, totalPaid: 1050, pendingAmount: 0,   pendingPaymentNote: '', startDate: '2025-08-10', status: 'ACTIVE' },
  { id: 'pp2', patientId: 'pa2', planTypeId: 'p1', totalSessions: 6,  usedSessions: 4, totalPaid: 325,  pendingAmount: 325, pendingPaymentNote: 'Acordó pagar la 2da cuota antes de la sesión 4 (esta semana)', startDate: '2025-10-05', status: 'ACTIVE' },
  { id: 'pp3', patientId: 'pa4', planTypeId: 'p2', totalSessions: 10, usedSessions: 2, totalPaid: 525,  pendingAmount: 525, pendingPaymentNote: 'Pagará 2da cuota la primera semana de junio (transferencia)', startDate: '2025-09-03', status: 'ACTIVE' },
  { id: 'pp4', patientId: 'pa5', planTypeId: 'p1', totalSessions: 6,  usedSessions: 6, totalPaid: 650,  pendingAmount: 0,   pendingPaymentNote: '', startDate: '2025-07-15', status: 'COMPLETED' },
  { id: 'pp5', patientId: 'pa7', planTypeId: 'p2', totalSessions: 10, usedSessions: 8, totalPaid: 1050, pendingAmount: 0,   pendingPaymentNote: '', startDate: '2025-06-20', status: 'ACTIVE' },
  { id: 'pp6', patientId: 'pa8', planTypeId: 'p1', totalSessions: 6,  usedSessions: 1, totalPaid: 650,  pendingAmount: 0,   pendingPaymentNote: '', startDate: '2026-02-14', status: 'ACTIVE' },
  { id: 'pp7', patientId: 'pa9', planTypeId: 'p3', totalSessions: 15, usedSessions: 4, totalPaid: 775,  pendingAmount: 775, pendingPaymentNote: 'Coordinó pago 2da cuota después del baby shower (mes 6)', startDate: '2025-12-01', status: 'ACTIVE' },
];

// Week of 2026-05-18 (Mon) to 2026-05-22 (Fri) — today is 2026-05-19 (Tue)
export const appointments: Appointment[] = [
  // Monday 2026-05-18 (all completed)
  { id: 'a1',  patientId: 'pa1',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-18T09:00', endTime: '2026-05-18T10:00', status: 'COMPLETED', patientPlanId: 'pp1', paymentStatus: 'PAID', paymentAmount: 105, paymentMethod: 'TRANSFER', notes: '', whatsappReminderSent: true, whatsappDayOfSent: true },
  { id: 'a2',  patientId: 'pa4',  therapistId: 't2', roomId: 'r2', startTime: '2026-05-18T09:00', endTime: '2026-05-18T10:00', status: 'COMPLETED', patientPlanId: 'pp3', paymentStatus: 'PAID', paymentAmount: 105, paymentMethod: 'CASH',     notes: '', whatsappReminderSent: true, whatsappDayOfSent: true },
  { id: 'a3',  patientId: 'pa7',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-18T10:00', endTime: '2026-05-18T11:00', status: 'COMPLETED', patientPlanId: 'pp5', paymentStatus: 'PAID', paymentAmount: 105, paymentMethod: 'YAPE',     notes: '', whatsappReminderSent: true, whatsappDayOfSent: true },
  { id: 'a4',  patientId: 'pa8',  therapistId: 't2', roomId: 'r2', startTime: '2026-05-18T10:00', endTime: '2026-05-18T11:00', status: 'COMPLETED', patientPlanId: 'pp6', paymentStatus: 'PAID', paymentAmount: 108, paymentMethod: 'CASH',     notes: '', whatsappReminderSent: true, whatsappDayOfSent: true },
  { id: 'a5',  patientId: 'pa9',  therapistId: 't3', roomId: 'r3', startTime: '2026-05-18T11:00', endTime: '2026-05-18T12:00', status: 'COMPLETED', patientPlanId: 'pp7', paymentStatus: 'PAID', paymentAmount: 103, paymentMethod: 'TRANSFER', notes: '', whatsappReminderSent: true, whatsappDayOfSent: true },
  { id: 'a6',  patientId: 'pa3',  therapistId: 't3', roomId: 'r3', startTime: '2026-05-18T14:00', endTime: '2026-05-18T15:00', status: 'NO_SHOW',   patientPlanId: null, paymentStatus: 'WAIVED', paymentAmount: 0, paymentMethod: null, notes: 'No avisó', whatsappReminderSent: true, whatsappDayOfSent: true },
  { id: 'a7',  patientId: 'pa10', therapistId: 't1', roomId: 'r1', startTime: '2026-05-18T15:00', endTime: '2026-05-18T16:00', status: 'COMPLETED', patientPlanId: null, paymentStatus: 'PAID', paymentAmount: 120, paymentMethod: 'PLIN',     notes: '', whatsappReminderSent: true, whatsappDayOfSent: true },
  { id: 'a8',  patientId: 'pa6',  therapistId: 't2', roomId: 'r2', startTime: '2026-05-18T16:00', endTime: '2026-05-18T17:00', status: 'COMPLETED', patientPlanId: null, paymentStatus: 'PAID', paymentAmount: 120, paymentMethod: 'TRANSFER', notes: '', whatsappReminderSent: true, whatsappDayOfSent: true },

  // Tuesday 2026-05-19 (today) — mix of statuses
  { id: 'a9',  patientId: 'pa2',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-19T09:00', endTime: '2026-05-19T10:00', status: 'CONFIRMED_TODAY', patientPlanId: 'pp2', paymentStatus: 'PAID',    paymentAmount: 108, paymentMethod: 'TRANSFER', notes: 'Traer ejercicios de la sesión anterior', whatsappReminderSent: true,  whatsappDayOfSent: true  },
  { id: 'a10', patientId: 'pa1',  therapistId: 't2', roomId: 'r2', startTime: '2026-05-19T10:00', endTime: '2026-05-19T11:00', status: 'CONFIRMED_TODAY', patientPlanId: 'pp1', paymentStatus: 'PAID',    paymentAmount: 105, paymentMethod: 'YAPE',     notes: '', whatsappReminderSent: true,  whatsappDayOfSent: true  },
  { id: 'a11', patientId: 'pa5',  therapistId: 't3', roomId: 'r3', startTime: '2026-05-19T11:00', endTime: '2026-05-19T12:00', status: 'CONFIRMED_24H',   patientPlanId: null,  paymentStatus: 'PENDING', paymentAmount: 120, paymentMethod: null,       notes: '', whatsappReminderSent: true,  whatsappDayOfSent: false },
  { id: 'a12', patientId: 'pa4',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-19T14:00', endTime: '2026-05-19T15:00', status: 'CONFIRMED_24H',   patientPlanId: 'pp3', paymentStatus: 'PENDING', paymentAmount: 105, paymentMethod: null,       notes: '', whatsappReminderSent: true,  whatsappDayOfSent: false },
  { id: 'a13', patientId: 'pa7',  therapistId: 't2', roomId: 'r2', startTime: '2026-05-19T15:00', endTime: '2026-05-19T16:00', status: 'CANCELLED',       patientPlanId: 'pp5', paymentStatus: 'WAIVED',  paymentAmount: 0,   paymentMethod: null,       notes: 'Paciente canceló por emergencia familiar', whatsappReminderSent: true, whatsappDayOfSent: false },
  { id: 'a14', patientId: 'pa9',  therapistId: 't3', roomId: 'r3', startTime: '2026-05-19T16:00', endTime: '2026-05-19T17:00', status: 'CONFIRMED_TODAY', patientPlanId: 'pp7', paymentStatus: 'PAID',    paymentAmount: 103, paymentMethod: 'CARD',     notes: '', whatsappReminderSent: true,  whatsappDayOfSent: true  },
  { id: 'a15', patientId: 'pa8',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-19T17:00', endTime: '2026-05-19T18:00', status: 'SCHEDULED',       patientPlanId: 'pp6', paymentStatus: 'PENDING', paymentAmount: 108, paymentMethod: null,       notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },

  // Wednesday 2026-05-20
  { id: 'a16', patientId: 'pa3',  therapistId: 't3', roomId: 'r3', startTime: '2026-05-20T09:00', endTime: '2026-05-20T10:00', status: 'CONFIRMED_24H', patientPlanId: null,  paymentStatus: 'PENDING', paymentAmount: 120, paymentMethod: null, notes: '', whatsappReminderSent: true,  whatsappDayOfSent: false },
  { id: 'a17', patientId: 'pa10', therapistId: 't1', roomId: 'r1', startTime: '2026-05-20T10:00', endTime: '2026-05-20T11:00', status: 'SCHEDULED',     patientPlanId: null,  paymentStatus: 'PENDING', paymentAmount: 120, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a18', patientId: 'pa6',  therapistId: 't2', roomId: 'r2', startTime: '2026-05-20T11:00', endTime: '2026-05-20T12:00', status: 'CONFIRMED_24H', patientPlanId: null,  paymentStatus: 'PENDING', paymentAmount: 120, paymentMethod: null, notes: '', whatsappReminderSent: true,  whatsappDayOfSent: false },
  { id: 'a19', patientId: 'pa1',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-20T14:00', endTime: '2026-05-20T15:00', status: 'SCHEDULED',     patientPlanId: 'pp1', paymentStatus: 'PENDING', paymentAmount: 105, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a20', patientId: 'pa2',  therapistId: 't2', roomId: 'r2', startTime: '2026-05-20T15:00', endTime: '2026-05-20T16:00', status: 'SCHEDULED',     patientPlanId: 'pp2', paymentStatus: 'PENDING', paymentAmount: 108, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a21', patientId: 'pa5',  therapistId: 't3', roomId: 'r3', startTime: '2026-05-20T16:00', endTime: '2026-05-20T17:00', status: 'SCHEDULED',     patientPlanId: null,  paymentStatus: 'PENDING', paymentAmount: 120, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a22', patientId: 'pa4',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-20T17:00', endTime: '2026-05-20T18:00', status: 'SCHEDULED',     patientPlanId: 'pp3', paymentStatus: 'PENDING', paymentAmount: 105, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },

  // Thursday 2026-05-21
  { id: 'a23', patientId: 'pa8',  therapistId: 't2', roomId: 'r2', startTime: '2026-05-21T09:00', endTime: '2026-05-21T10:00', status: 'SCHEDULED', patientPlanId: 'pp6', paymentStatus: 'PENDING', paymentAmount: 108, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a24', patientId: 'pa9',  therapistId: 't3', roomId: 'r3', startTime: '2026-05-21T10:00', endTime: '2026-05-21T11:00', status: 'SCHEDULED', patientPlanId: 'pp7', paymentStatus: 'PENDING', paymentAmount: 103, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a25', patientId: 'pa7',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-21T11:00', endTime: '2026-05-21T12:00', status: 'SCHEDULED', patientPlanId: 'pp5', paymentStatus: 'PENDING', paymentAmount: 105, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a26', patientId: 'pa3',  therapistId: 't3', roomId: 'r3', startTime: '2026-05-21T14:00', endTime: '2026-05-21T15:00', status: 'SCHEDULED', patientPlanId: null,  paymentStatus: 'PENDING', paymentAmount: 120, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a27', patientId: 'pa10', therapistId: 't2', roomId: 'r2', startTime: '2026-05-21T15:00', endTime: '2026-05-21T16:00', status: 'SCHEDULED', patientPlanId: null,  paymentStatus: 'PENDING', paymentAmount: 120, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a28', patientId: 'pa6',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-21T16:00', endTime: '2026-05-21T17:00', status: 'SCHEDULED', patientPlanId: null,  paymentStatus: 'PENDING', paymentAmount: 120, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },

  // Friday 2026-05-22
  { id: 'a29', patientId: 'pa1',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-22T09:00', endTime: '2026-05-22T10:00', status: 'SCHEDULED', patientPlanId: 'pp1', paymentStatus: 'PENDING', paymentAmount: 105, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a30', patientId: 'pa2',  therapistId: 't3', roomId: 'r3', startTime: '2026-05-22T10:00', endTime: '2026-05-22T11:00', status: 'SCHEDULED', patientPlanId: 'pp2', paymentStatus: 'PENDING', paymentAmount: 108, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a31', patientId: 'pa4',  therapistId: 't2', roomId: 'r2', startTime: '2026-05-22T11:00', endTime: '2026-05-22T12:00', status: 'SCHEDULED', patientPlanId: 'pp3', paymentStatus: 'PENDING', paymentAmount: 105, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a32', patientId: 'pa5',  therapistId: 't1', roomId: 'r1', startTime: '2026-05-22T14:00', endTime: '2026-05-22T15:00', status: 'SCHEDULED', patientPlanId: null,  paymentStatus: 'PENDING', paymentAmount: 120, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a33', patientId: 'pa8',  therapistId: 't3', roomId: 'r3', startTime: '2026-05-22T15:00', endTime: '2026-05-22T16:00', status: 'SCHEDULED', patientPlanId: 'pp6', paymentStatus: 'PENDING', paymentAmount: 108, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
  { id: 'a34', patientId: 'pa9',  therapistId: 't2', roomId: 'r2', startTime: '2026-05-22T17:00', endTime: '2026-05-22T18:00', status: 'SCHEDULED', patientPlanId: 'pp7', paymentStatus: 'PENDING', paymentAmount: 103, paymentMethod: null, notes: '', whatsappReminderSent: false, whatsappDayOfSent: false },
];

export const clinicalNotes: ClinicalNote[] = [
  {
    id: 'cn1', appointmentId: 'a1', therapistId: 't1', createdAt: '2026-05-18T10:30',
    reason: 'Dolor lumbar persistente desde la semana pasada',
    painLevel: 3,
    positionsWorked: ['boca abajo', 'de costado'],
    machinesUsed: 'Tens, ultrasonido lumbar',
    acupuncture: 'si', acupunctureDetail: 'Puntos lumbares B23, B25',
    traction: 'si', tractionDetail: '', tractionType: 'lumbar', tractionTypeDetail: '',
    manual: 'si', manualDetail: 'Movilización lumbar',
    chiropractic: 'no', chiropracticDetail: '',
    observations: 'Mejora notable en rango de movimiento. Sin dolor irradiado hoy.',
  },
  {
    id: 'cn2', appointmentId: 'a2', therapistId: 't2', createdAt: '2026-05-18T10:30',
    reason: 'Control evolución tendinitis rotuliana',
    painLevel: 5,
    positionsWorked: ['boca arriba', 'lado derecho'],
    machinesUsed: 'Crioterapia, ultrasonido rodilla',
    acupuncture: 'no', acupunctureDetail: '',
    traction: 'no', tractionDetail: '', tractionType: '', tractionTypeDetail: '',
    manual: 'si', manualDetail: 'Liberación miofascial cuádriceps',
    chiropractic: 'no', chiropracticDetail: '',
    observations: 'Buen progreso. Indicar fortalecimiento isométrico en casa.',
  },
  {
    id: 'cn3', appointmentId: 'a3', therapistId: 't1', createdAt: '2026-05-18T11:30',
    reason: 'Cervicalgia y migraña tensional',
    painLevel: 3,
    positionsWorked: ['boca arriba'],
    machinesUsed: 'Tens cervical',
    acupuncture: 'si', acupunctureDetail: 'Puntos cervicales y trapecio',
    traction: 'si', tractionDetail: '', tractionType: 'cervical', tractionTypeDetail: '',
    manual: 'si', manualDetail: 'Masaje cervical profundo',
    chiropractic: 'no', chiropracticDetail: '',
    observations: 'Reduce dolor de forma sostenida. Buena respuesta.',
  },
  {
    id: 'cn5', appointmentId: 'a5', therapistId: 't3', createdAt: '2026-05-18T12:30',
    reason: 'Control prenatal, dolor lumbar tercer trimestre',
    painLevel: 4,
    positionsWorked: ['de costado', 'lado izquierdo'],
    machinesUsed: '',
    acupuncture: 'no', acupunctureDetail: '',
    traction: 'no', tractionDetail: '', tractionType: '', tractionTypeDetail: '',
    manual: 'si', manualDetail: 'Técnicas suaves específicas para gestantes',
    chiropractic: 'no', chiropracticDetail: '',
    observations: 'Paciente refiere alivio importante. Cuidado con la posición decúbito supino.',
  },
  {
    id: 'cn7', appointmentId: 'a7', therapistId: 't1', createdAt: '2026-05-18T16:30',
    reason: 'Túnel carpiano y dolor cervical por postura',
    painLevel: 3,
    positionsWorked: ['boca arriba'],
    machinesUsed: 'Tens muñeca, ultrasonido',
    acupuncture: 'otros', acupunctureDetail: 'Electroacupuntura en muñeca derecha',
    traction: 'no', tractionDetail: '', tractionType: '', tractionTypeDetail: '',
    manual: 'si', manualDetail: 'Neurodinamia nervio mediano',
    chiropractic: 'no', chiropracticDetail: '',
    observations: 'Buena tolerancia. Recomendar pausas activas en la jornada.',
  },
  {
    id: 'cn8', appointmentId: 'a8', therapistId: 't2', createdAt: '2026-05-18T17:30',
    reason: 'Lumbalgia recurrente, hernia L5-S1',
    painLevel: 6,
    positionsWorked: ['boca abajo', 'ambos lados'],
    machinesUsed: 'Ultrasonido, tens lumbar',
    acupuncture: 'si', acupunctureDetail: 'Puntos lumbares y miembro inferior',
    traction: 'si', tractionDetail: '', tractionType: 'lumbar', tractionTypeDetail: '',
    manual: 'si', manualDetail: 'Movilización articular vertebral',
    chiropractic: 'otros', chiropracticDetail: 'Ajuste con técnica suave de Thompson',
    observations: 'Sesión intensa pero bien tolerada. Sin dolor ciático irradiado.',
  },
];

export const whatsAppConfig: WhatsAppConfig = {
  accountSid: 'ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  authToken: '••••••••••••••••••••••••••••••••',
  fromNumber: '+51912345000',
  template24h: 'Hola {nombre} 👋 Te recordamos que mañana tienes sesión con {terapeuta} a las {hora}. Para confirmar responde *1*, para cancelar responde *2*.',
  templateDayOf: 'Hola {nombre}! Hoy tienes sesión con {terapeuta} a las {hora}. ¡Te esperamos! 🌟',
};

export const inventoryItems: InventoryItem[] = [
  { id: 'i1',  name: 'Agujas de acupuntura desechables', unit: 'unidades', currentStock: 280, minStock: 100 },
  { id: 'i2',  name: 'Papel camilla',                    unit: 'rollos',   currentStock: 8,   minStock: 5 },
  { id: 'i3',  name: 'Jabón líquido antibacterial',      unit: 'litros',   currentStock: 12,  minStock: 4 },
  { id: 'i4',  name: 'Alcohol en gel',                   unit: 'litros',   currentStock: 6,   minStock: 3 },
  { id: 'i5',  name: 'Aceite para masaje',               unit: 'litros',   currentStock: 4,   minStock: 2 },
  { id: 'i6',  name: 'Guantes desechables',              unit: 'cajas',    currentStock: 3,   minStock: 4 },
  { id: 'i7',  name: 'Toallas desechables',              unit: 'paquetes', currentStock: 18,  minStock: 6 },
  { id: 'i8',  name: 'Electrodos para Tens',             unit: 'pares',    currentStock: 24,  minStock: 8 },
  { id: 'i9',  name: 'Gel conductor para ultrasonido',   unit: 'frascos',  currentStock: 5,   minStock: 2 },
];

export const inventoryPurchases: InventoryPurchase[] = [
  { id: 'ip1', itemId: 'i1', quantity: 200, date: '2026-05-10', notes: 'Compra mensual rutinaria' },
  { id: 'ip2', itemId: 'i2', quantity: 12,  date: '2026-05-10', notes: '' },
  { id: 'ip3', itemId: 'i3', quantity: 8,   date: '2026-05-12', notes: '' },
  { id: 'ip4', itemId: 'i5', quantity: 4,   date: '2026-05-15', notes: 'Marca premium' },
  { id: 'ip5', itemId: 'i8', quantity: 16,  date: '2026-05-18', notes: '' },
];

export const payments: Payment[] = [
  { id: 'pay1', date: '2026-05-18T10:00', patientId: 'pa1', amount: 105, paymentMethod: 'TRANSFER', observation: 'Sesión 6/10 del Pack 10', evidencePhotoUrl: null, relatedTo: 'appointment', relatedId: 'a1' },
  { id: 'pay2', date: '2026-05-18T10:00', patientId: 'pa4', amount: 105, paymentMethod: 'CASH',     observation: 'Sesión 2/10',             evidencePhotoUrl: null, relatedTo: 'appointment', relatedId: 'a2' },
  { id: 'pay3', date: '2026-05-18T11:00', patientId: 'pa7', amount: 105, paymentMethod: 'YAPE',     observation: 'Sesión 8/10',             evidencePhotoUrl: null, relatedTo: 'appointment', relatedId: 'a3' },
  { id: 'pay4', date: '2026-05-18T11:00', patientId: 'pa8', amount: 108, paymentMethod: 'CASH',     observation: 'Sesión 1/6',              evidencePhotoUrl: null, relatedTo: 'appointment', relatedId: 'a4' },
  { id: 'pay5', date: '2026-05-18T12:00', patientId: 'pa9', amount: 103, paymentMethod: 'TRANSFER', observation: 'Sesión 4/15 — gestante',  evidencePhotoUrl: null, relatedTo: 'appointment', relatedId: 'a5' },
  { id: 'pay6', date: '2026-05-18T16:00', patientId: 'pa10', amount: 120, paymentMethod: 'PLIN',    observation: 'Sesión individual',       evidencePhotoUrl: null, relatedTo: 'appointment', relatedId: 'a7' },
  { id: 'pay7', date: '2026-05-18T17:00', patientId: 'pa6', amount: 120, paymentMethod: 'TRANSFER', observation: 'Sesión individual',       evidencePhotoUrl: null, relatedTo: 'appointment', relatedId: 'a8' },
  { id: 'pay8', date: '2026-05-19T10:00', patientId: 'pa2', amount: 108, paymentMethod: 'TRANSFER', observation: 'Sesión 4/6',              evidencePhotoUrl: null, relatedTo: 'appointment', relatedId: 'a9' },
  { id: 'pay9', date: '2026-05-19T11:00', patientId: 'pa1', amount: 105, paymentMethod: 'YAPE',     observation: 'Sesión 7/10',             evidencePhotoUrl: null, relatedTo: 'appointment', relatedId: 'a10' },
  { id: 'pay10', date: '2026-05-19T17:00', patientId: 'pa9', amount: 103, paymentMethod: 'CARD',    observation: 'Sesión 5/15',             evidencePhotoUrl: null, relatedTo: 'appointment', relatedId: 'a14' },
  { id: 'pay11', date: '2026-05-15T09:00', patientId: 'pa2', amount: 325, paymentMethod: 'CASH',    observation: 'Primera cuota Pack 6',    evidencePhotoUrl: null, relatedTo: 'plan', relatedId: 'pp2' },
  { id: 'pay12', date: '2026-05-10T09:00', patientId: 'pa4', amount: 525, paymentMethod: 'TRANSFER', observation: 'Primera cuota Pack 10',  evidencePhotoUrl: null, relatedTo: 'plan', relatedId: 'pp3' },
  { id: 'pay13', date: '2026-05-01T09:00', patientId: 'pa9', amount: 775, paymentMethod: 'TRANSFER', observation: 'Primera cuota Pack 15',  evidencePhotoUrl: null, relatedTo: 'plan', relatedId: 'pp7' },
];
